- name: variables to print
  hosts: web
  vars:
    COURSE: "Devops with AWS"
    DURTATION: "120HR"
    TRAINER: "Siva Kumar Reddy Marella"
  tasks:
    - name: print the information
      ansible.builtin.debug:
        msg: "I am Learning {{COURSE}} and {{DURTATION}} is : 120 HR and the {{TRAINER}} is : SivaKumar Reddy M"
