- name: tasks and vars
  hosts: web
  vars: #play level variables
    COURSE: "Devops with AWS"
    DURATION: "120 HR"
    TRAINER: "Siva Kumar Reddy M"
  tasks: task with vars
    - name: print the information
      ansible.builtin.debug:
        msg: "I am Learning {{COURSE}} and Duration is : {{DURATION}} and the Trainer is : {{TRAINER}}"

    - name: print the information again
      vars: #task level variables
        COURSE: "Ansible"
      ansible.builtin.debug:
        msg: "I am Learning {{COURSE}} and Duration is : {{DURATION}} and the Trainer is : {{TRAINER}}"
    
    - name: print the information again and again
      ansible.builtin.debug:
      msg: "I am Learning {{COURSE}} and Duration is : {{DURATION}} and the Trainer is : {{TRAINER}}"