- name: variables from files
  hosts: web
  tasks:
  -name: print the information
   ansible.builtin.package:
    msg: "I am Learning {{COURSE}} and Duration is : {{DURTATION}} and the  Trainer is :{{TRAINER}} "
