- name: variables from files
  hosts: web
  vars-files:
    - vars.yaml
  tasks:
    - name: variables from files
      ansible.builtin.package:
        msg: "I am Learning {{COURSE}} and Duration is : {{DURTATION}} and the  Trainer is :{{TRAINER}} "
