- name: variables from prompt
  hosts: web
  vars_prompt:
    - name: COURSE
      prompt: Please Enter Course Name
    - name: DURATION
      prompt: Please Enter Duration
    - name: TRAINER
      prompt: Please Enter Trainer Name
  tasks:
    - name: variable from command prompt
      ansible.builtin.debug:
        msg: "I am Learning with {{COURSE}} and Duration is : {{DURATION}} and the Trainer is {{TRAINER}}"
