- name: check a number is less than 10 or not
  hosts: local
  connection: local
  vars_prompt:
    - name: number
      prompt: Please enter number
      private: false # not confidential
  # vars:
  #   number: 139
  tasks:
    - name: print this if less than 10
      ansible.builtin.debug:
        msg: "Given number is {{number}} less than 10"
      when: number | int < 10 # condition expression

    - name: print this if greater than 10
      ansible.builtin.debug:
        msg: "Given number is {{number}}  greater than or equal 10"
      when: number | int >= 10
