- name: print the names
  hosts: web
  tasks:
    - name: print names
      ansible.builtin.debug:
        msg: "Hello {{item}}"
      loop:
        - Suresh
        - Mahesh
        - Ramesh
        - Sakalesh
