- name: loop the package
  hosts: web
  become: yes
  tasks:
    - name: loop the package
      ansible.builtin.package:
        name: "{{item}}"
        state: present
      loop:
        - mysql
        - nginx
        - postfix
        - httpd
