- name: loops the packages
  hosts: web
  become: yes
  tasks:
    - name: print the packages
      anisble.builtin.package:
        name: "{ { item.name } }"
        state: "{ { item.state } }"
      loop:
        - { name: mysql, state: present }
        - { name: nginx, state: absent }
        - { name: postfix, state: present }
        - { name: httpd, state: absent }
